name: Javascript CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['dev', 'main']

env:
  CARGO_TERM_COLOR: always

jobs:
  webapp_build:
    name: Check web app build
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node-version: [16.x]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Run lib-wasm build
        working-directory: ./packages/lib-wasm
        run: wasm-pack build --release --target web --out-dir ${{ github.workspace }}/target/wasm

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Rename wasm package
        run: |
          npm install replace -g 
          replace "sds-wasm" "@essex/sds-core" ./target/wasm/package.json

      - name: Install dependencies
        run: yarn install

      - name: CI
        run: yarn git:ci

      - name: Check for uncommitted changes
        run: git diff-index --quiet HEAD --

      - name: Publish wasm core
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn release
