name: Rust CI

on:
  push:
    branches: ['rust-ci']
  pull_request:
    branches: ['rust-ci']

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo_build:
    name: Check overall build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run cargo build release
        run: cargo build --verbose --release

  cargo_fmt:
    name: Check code format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  cargo_clippy:
    name: Check clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings

  cargo_test:
    name: Run cargo tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run cargo test
        run: cargo test --verbose

  lib_wasm_build:
    name: Check lib-wasm build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Run wasm-pack build
        working-directory: ./packages/lib-wasm
        run: wasm-pack build --release --target web --out-dir ${{ github.workspace }}/target/wasm
