name: Rust CI

on:
  push:
    branches: ['rust-ci']
  pull_request:
    branches: ['rust-ci']

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo_build:
    name: Check all packages are properly building
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run cargo build release
        run: cargo build --verbose --release

  cargo_test:
    name: Run cargo tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run cargo test
        run: cargo test --verbose

  cargo_fmt:
    name: Check code is properly formatted
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  cargo_clippy:
    name: Check clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install clippy
        run: rustup component add clippy

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings
